### ISSUE TITLE
Request to add fragments with halogens to the list

### ISSUE THREAD

**Issue by Sowmya-R-Krishnan** [OpenChemistry/molecules#1]
Thanks for sharing these fragments with the community.
Is it possible to have molecular fragments with halogen atoms in the list (like alkyl halides, fluorobenzene etc.,)? Could not find any fragment with halogen atoms in the list. It will be really helpful to know which halogen-containing fragments are commonly found in organic molecules.

**Comment by ghutchis** [comment]
Do you have suggestions for molecules to add? It's pretty easy to generate the fragments, but knowing what to add would be helpful (e.g., through Wikipedia perhaps?)

**Comment by Sowmya-R-Krishnan** [comment]
Thanks for the reply. I think the categories in this Wiki page will cover most of the halogen-containing organic molecules: https://en.wikipedia.org/wiki/Halocarbon - Haloalkanes, Haloalkenes and Haloaromatics. Is this helpful?

**Comment by ghutchis** [comment]
If you can get a list of URLs for compound pages or SMILES from the pages, it would be a huge help, e.g.
https://en.wikipedia.org/wiki/Bromomethane
https://en.wikipedia.org/wiki/Tetrachloroethylene
https://en.wikipedia.org/wiki/DDT
https://en.wikipedia.org/wiki/Tetrabromobisphenol_A

The category pages are probably the most useful, e.g.
https://en.wikipedia.org/wiki/Category:Organohalides
https://en.wikipedia.org/wiki/Category:Organochlorides

The problem is basically that I want to include the most useful / popular so it requires some human curation. Other databases like PubChem include everything.
